controller_joint_names: ['', 'front_right_wheel_connector_to_front_right_wheel', 'front_left_wheel_connector_to_front_left_wheel', 'back_right_wheel_connector_to_back_right_wheel', 'back_left_wheel_connector_to_back_left_wheel', ]
